#!/usr/bin/env python3
"""Single source of truth for the Dangerous Fungi add-on.

Every block definition, texture, geometry, particle, world-generation feature,
language string and script data table is generated from the SPECIES table below,
so the twenty fungi can never drift out of sync with each other.

Target: Minecraft Bedrock 1.21.0 (Android / Pocket Edition, build 1.21.0.26).
Only stable data-driven features and @minecraft/server 1.11.0 are used.
"""

NAMESPACE = "fungi"

BP_DIR = "behavior_packs/dangerous_fungi_bp"
RP_DIR = "resource_packs/dangerous_fungi_rp"
BP_FOLDER = "dangerous_fungi_bp"
RP_FOLDER = "dangerous_fungi_rp"

ADDON_NAME = "Dangerous_Fungi.mcaddon"
PACK_VERSION = [1, 0, 0]
MIN_ENGINE = [1, 21, 0]
SERVER_MODULE = "1.11.0"

# Manifest UUIDs. Fixed so that re-running the generator never invalidates an
# install that is already on a device.
UUIDS = {
    "bp_header": "7c1e0b62-4b3d-4b7a-9f2c-8a1d5e6f3a01",
    "bp_data": "7c1e0b62-4b3d-4b7a-9f2c-8a1d5e6f3a02",
    "bp_script": "7c1e0b62-4b3d-4b7a-9f2c-8a1d5e6f3a03",
    "rp_header": "7c1e0b62-4b3d-4b7a-9f2c-8a1d5e6f3a04",
    "rp_resources": "7c1e0b62-4b3d-4b7a-9f2c-8a1d5e6f3a05",
}

# Vanilla sound sets for mining, stepping on, breaking and placing each
# species. The resource pack's blocks.json is the only place a data-driven
# block can get sounds - without an entry there a custom block is completely
# silent. Every name below exists in vanilla 1.21.0.
SOUNDS = {
    "bloodcap": "grass",
    "toxic_veil": "grass",
    "sporeburst": "grass",
    "shadow_morel": "grass",
    "embercap": "nether_wart",
    "frost_mold": "snow",
    "rotcap": "grass",
    "phantom_fungus": "cloth",
    "shockshroom": "amethyst_block",
    "acid_bloom": "slime",
    "voidcap": "sculk",
    "spine_fungus": "stone",
    "crimson_brain": "nether_wart",
    "glowspore": "moss",
    "deathbell": "grass",
    "creeping_mold": "moss",
    "ash_fungus": "gravel",
    "nightmare_cap": "grass",
    "parasite_bloom": "slime",
    "mycelium_x": "sculk",
}

DANGER_NAMES = {
    1: "LEVEL I - IRRITANT",
    2: "LEVEL II - HARMFUL",
    3: "LEVEL III - TOXIC",
    4: "LEVEL IV - EXTREMELY DANGEROUS",
    5: "LEVEL V - CATASTROPHIC",
}

# --------------------------------------------------------------------------
# Block id presets used by the world-generation features.
# Every id below exists in vanilla 1.21.0.
# --------------------------------------------------------------------------

GROUND = [
    "minecraft:dirt",
    "minecraft:grass_block",
    "minecraft:podzol",
    "minecraft:mycelium",
    "minecraft:moss_block",
]
STONE = [
    "minecraft:stone",
    "minecraft:deepslate",
    "minecraft:andesite",
    "minecraft:diorite",
    "minecraft:granite",
    "minecraft:tuff",
    "minecraft:gravel",
    "minecraft:dirt",
]
DEEP = [
    "minecraft:deepslate",
    "minecraft:sculk",
    "minecraft:stone",
    "minecraft:tuff",
]
NETHER = [
    "minecraft:netherrack",
    "minecraft:soul_soil",
    "minecraft:crimson_nylium",
    "minecraft:warped_nylium",
    "minecraft:basalt",
    "minecraft:blackstone",
]
SWAMP = [
    "minecraft:dirt",
    "minecraft:grass_block",
    "minecraft:mud",
    "minecraft:clay",
    "minecraft:moss_block",
    "minecraft:podzol",
]
COLD = [
    "minecraft:snow",
    "minecraft:snow_layer",
    "minecraft:packed_ice",
    "minecraft:dirt",
    "minecraft:grass_block",
    "minecraft:stone",
]


def surface(biomes, attach, iterations=1, chance=(1, 6)):
    return {
        "pass": "surface_pass",
        "biomes": biomes,
        "attach": attach,
        "iterations": iterations,
        "chance": chance,
        "y": None,
    }


def underground(y, attach, biomes=("overworld",), iterations=2, chance=(1, 6)):
    return {
        "pass": "underground_pass",
        "biomes": list(biomes),
        "attach": attach,
        "iterations": iterations,
        "chance": chance,
        "y": y,
    }


# --------------------------------------------------------------------------
# The twenty species.
#
#   danger        1..5, drives the scanner readout and the protection maths
#   shape         geometry family (see tools/gen_fungi.py SHAPES)
#   range         radius in blocks at which the aura reaches a player
#   damage        hit points removed per one-second aura tick (0 = none)
#   contact       extra damage when a player is inside the block's own space
#   pulse         aura fires once every N seconds instead of every second
#   effects       [(effect id, duration ticks, amplifier), ...]
#   light         block light emission, 0..15
#   flammable     burns when set alight
#   palette       cap/stem/highlight/shadow/accent/glow colours
#   cap_style     texture generator for the cap material
#   stem_style    texture generator for the stem material
#   particle      tint + motion preset for the ambient particle effect
# --------------------------------------------------------------------------

SPECIES = [
    {
        "key": "bloodcap",
        "name": "Bloodcap Fungus",
        "danger": 3,
        "shape": "cap_broad",
        "range": 3.0,
        "damage": 1.0,
        "contact": 1.0,
        "pulse": 1,
        "effects": [("wither", 60, 0)],
        "light": 0,
        "flammable": True,
        "palette": {
            "cap": (139, 26, 26),
            "cap_dark": (74, 13, 13),
            "cap_light": (196, 43, 43),
            "accent": (232, 215, 195),
            "stem": (222, 205, 188),
            "stem_dark": (150, 133, 118),
            "glow": None,
        },
        "cap_style": "spots",
        "stem_style": "fibrous",
        "particle": {"style": "rise", "color": (0.72, 0.10, 0.10), "size": 0.055},
        "gen": underground((-40, 45), STONE, iterations=3, chance=(1, 5)),
        "habitat": "Damp cave walls and abandoned mineshafts.",
        "desc": "A crimson cap that weeps a corrosive red mist. Standing close drains the blood.",
    },
    {
        "key": "toxic_veil",
        "name": "Toxic Veil",
        "danger": 2,
        "shape": "veil",
        "range": 3.5,
        "damage": 0.0,
        "contact": 0.0,
        "pulse": 1,
        "effects": [("poison", 80, 0)],
        "light": 0,
        "flammable": True,
        "palette": {
            "cap": (63, 163, 77),
            "cap_dark": (30, 91, 42),
            "cap_light": (111, 217, 122),
            "accent": (201, 245, 66),
            "stem": (86, 140, 74),
            "stem_dark": (44, 84, 40),
            "glow": None,
        },
        "cap_style": "veined",
        "stem_style": "fibrous",
        "particle": {"style": "drift", "color": (0.28, 0.75, 0.30), "size": 0.05},
        "gen": surface(["swamp"], SWAMP, iterations=2, chance=(1, 4)),
        "habitat": "Swamp shallows and rotting wood.",
        "desc": "A drooping lattice of green threads that sheds poison whenever it is brushed.",
    },
    {
        "key": "sporeburst",
        "name": "Sporeburst Mushroom",
        "danger": 2,
        "shape": "puffball",
        "range": 3.0,
        "damage": 0.0,
        "contact": 0.0,
        "pulse": 2,
        "effects": [("nausea", 80, 0), ("blindness", 20, 0)],
        "light": 0,
        "flammable": True,
        "palette": {
            "cap": (201, 194, 168),
            "cap_dark": (138, 131, 104),
            "cap_light": (232, 226, 204),
            "accent": (255, 255, 255),
            "stem": (168, 160, 136),
            "stem_dark": (110, 104, 84),
            "glow": None,
        },
        "cap_style": "warts",
        "stem_style": "smooth",
        "particle": {"style": "burst", "color": (0.85, 0.83, 0.72), "size": 0.07},
        "gen": surface(["forest"], GROUND, iterations=2, chance=(1, 4)),
        "habitat": "Forest floors and leaf litter.",
        "desc": "A taut puffball. Any disturbance splits the skin and floods the air with choking spores.",
    },
    {
        "key": "shadow_morel",
        "name": "Shadow Morel",
        "danger": 3,
        "shape": "morel",
        "range": 3.5,
        "damage": 0.0,
        "contact": 0.0,
        "pulse": 1,
        "effects": [("blindness", 70, 0)],
        "light": 0,
        "flammable": False,
        "palette": {
            "cap": (46, 36, 56),
            "cap_dark": (23, 17, 29),
            "cap_light": (74, 60, 87),
            "accent": (107, 91, 123),
            "stem": (78, 70, 84),
            "stem_dark": (40, 35, 46),
            "glow": None,
        },
        "cap_style": "honeycomb",
        "stem_style": "ribbed",
        "particle": {"style": "sink", "color": (0.16, 0.12, 0.22), "size": 0.06},
        "gen": underground((-55, 10), STONE, iterations=2, chance=(1, 7)),
        "habitat": "Lightless caverns far from any torch.",
        "desc": "Grows only where no light reaches. Its pitted cap swallows the dark and gives it back.",
    },
    {
        "key": "embercap",
        "name": "Embercap",
        "danger": 4,
        "shape": "cap_glow",
        "range": 3.0,
        "damage": 2.0,
        "contact": 2.0,
        "pulse": 1,
        "effects": [],
        "light": 11,
        "flammable": False,
        "ignites": True,
        "palette": {
            "cap": (226, 87, 30),
            "cap_dark": (122, 36, 8),
            "cap_light": (255, 162, 58),
            "accent": (255, 216, 77),
            "stem": (94, 52, 36),
            "stem_dark": (52, 26, 18),
            "glow": (255, 216, 77),
        },
        "cap_style": "cracks",
        "stem_style": "bark",
        "particle": {"style": "rise", "color": (1.0, 0.55, 0.15), "size": 0.05, "glow": True},
        "gen": surface(["nether"], NETHER, iterations=3, chance=(1, 4)),
        "habitat": "Nether wastes and basalt fields.",
        "desc": "Its cap holds a living coal. Anything that lingers beside it catches light.",
    },
    {
        "key": "frost_mold",
        "name": "Frost Mold",
        "danger": 2,
        "shape": "crust",
        "range": 3.5,
        "damage": 0.0,
        "contact": 0.0,
        "pulse": 1,
        "effects": [("slowness", 90, 1)],
        "light": 0,
        "flammable": False,
        "palette": {
            "cap": (159, 216, 232),
            "cap_dark": (78, 140, 168),
            "cap_light": (221, 244, 255),
            "accent": (255, 255, 255),
            "stem": (140, 190, 210),
            "stem_dark": (70, 120, 145),
            "glow": None,
        },
        "cap_style": "crystal",
        "stem_style": "smooth",
        "particle": {"style": "sink", "color": (0.70, 0.90, 1.0), "size": 0.045},
        "gen": surface(["cold"], COLD, iterations=3, chance=(1, 4)),
        "habitat": "Snowfields, ice sheets and frozen peaks.",
        "desc": "A creeping rime that steals the warmth out of anything standing on it.",
    },
    {
        "key": "rotcap",
        "name": "Rotcap",
        "danger": 2,
        "shape": "droop",
        "range": 3.0,
        "damage": 0.0,
        "contact": 0.0,
        "pulse": 1,
        "effects": [("hunger", 120, 0), ("weakness", 120, 0)],
        "light": 0,
        "flammable": True,
        "palette": {
            "cap": (107, 106, 58),
            "cap_dark": (59, 58, 30),
            "cap_light": (142, 140, 85),
            "accent": (74, 91, 42),
            "stem": (120, 116, 88),
            "stem_dark": (66, 63, 46),
            "glow": None,
        },
        "cap_style": "mottle",
        "stem_style": "fibrous",
        "particle": {"style": "drift", "color": (0.42, 0.42, 0.22), "size": 0.05},
        "gen": surface(["swamp", "forest"], SWAMP, iterations=2, chance=(1, 5)),
        "habitat": "Rotting logs in swamps and old forests.",
        "desc": "Sags under its own decay. The stink alone hollows out a stomach.",
    },
    {
        "key": "phantom_fungus",
        "name": "Phantom Fungus",
        "danger": 3,
        "shape": "phantom_veil",
        "range": 4.0,
        "damage": 0.0,
        "contact": 0.0,
        "pulse": 1,
        "effects": [("nausea", 100, 0), ("blindness", 25, 0)],
        "light": 4,
        "flammable": False,
        "palette": {
            "cap": (200, 214, 229),
            "cap_dark": (143, 163, 184),
            "cap_light": (237, 244, 250),
            "accent": (168, 232, 255),
            "stem": (176, 194, 212),
            "stem_dark": (120, 138, 158),
            "glow": (168, 232, 255),
        },
        "cap_style": "wisp",
        "stem_style": "smooth",
        "particle": {"style": "drift", "color": (0.78, 0.88, 1.0), "size": 0.06, "glow": True},
        "gen": underground((-45, 20), STONE, iterations=1, chance=(1, 14)),
        "habitat": "Deep, still caves. Rare.",
        "desc": "Barely there. It thins the air until direction stops meaning anything.",
    },
    {
        "key": "shockshroom",
        "name": "Shockshroom",
        "danger": 4,
        "shape": "antenna",
        "range": 3.0,
        "damage": 3.0,
        "contact": 0.0,
        "pulse": 3,
        "effects": [],
        "light": 7,
        "flammable": False,
        "palette": {
            "cap": (47, 127, 224),
            "cap_dark": (20, 63, 128),
            "cap_light": (127, 196, 255),
            "accent": (223, 243, 255),
            "stem": (60, 90, 130),
            "stem_dark": (28, 46, 72),
            "glow": (200, 240, 255),
        },
        "cap_style": "arcs",
        "stem_style": "ribbed",
        "particle": {"style": "spark", "color": (0.45, 0.75, 1.0), "size": 0.05, "glow": True},
        "gen": underground((-50, 30), STONE, iterations=2, chance=(1, 8)),
        "habitat": "Ore-rich cave systems.",
        "desc": "Stores a charge in its stalk and dumps it into anything nearby every few seconds.",
    },
    {
        "key": "acid_bloom",
        "name": "Acid Bloom",
        "danger": 3,
        "shape": "bowl",
        "range": 2.5,
        "damage": 0.0,
        "contact": 3.0,
        "pulse": 1,
        "effects": [("poison", 70, 1)],
        "light": 0,
        "flammable": False,
        "palette": {
            "cap": (184, 212, 0),
            "cap_dark": (110, 127, 0),
            "cap_light": (230, 255, 77),
            "accent": (255, 255, 160),
            "stem": (140, 160, 40),
            "stem_dark": (80, 94, 20),
            "glow": None,
        },
        "cap_style": "goo",
        "stem_style": "smooth",
        "particle": {"style": "drip", "color": (0.78, 0.90, 0.10), "size": 0.05},
        "gen": surface(["jungle", "swamp"], SWAMP, iterations=2, chance=(1, 6)),
        "habitat": "Humid jungle basins and swamp edges.",
        "desc": "An open cup brimming with something that eats through boots.",
    },
    {
        "key": "voidcap",
        "name": "Voidcap",
        "danger": 4,
        "shape": "cap_spire",
        "range": 3.0,
        "damage": 2.0,
        "contact": 2.0,
        "pulse": 1,
        "effects": [("darkness", 120, 0), ("mining_fatigue", 100, 0)],
        "light": 0,
        "flammable": False,
        "palette": {
            "cap": (43, 18, 63),
            "cap_dark": (18, 7, 32),
            "cap_light": (90, 42, 128),
            "accent": (179, 102, 255),
            "stem": (52, 40, 66),
            "stem_dark": (26, 18, 36),
            "glow": (140, 70, 220),
        },
        "cap_style": "rift",
        "stem_style": "ribbed",
        "particle": {"style": "sink", "color": (0.35, 0.10, 0.60), "size": 0.06, "glow": True},
        "gen": underground((-60, -20), DEEP, iterations=2, chance=(1, 9)),
        "habitat": "The deepest deepslate, near sculk. Deep Dark depths.",
        "desc": "A cap that is mostly absence. Light bends into it and does not come back.",
    },
    {
        "key": "spine_fungus",
        "name": "Spine Fungus",
        "danger": 3,
        "shape": "spikes",
        "range": 2.0,
        "damage": 0.0,
        "contact": 4.0,
        "pulse": 1,
        "effects": [],
        "light": 0,
        "flammable": False,
        "hurts_mobs": True,
        "palette": {
            "cap": (122, 110, 102),
            "cap_dark": (62, 56, 51),
            "cap_light": (168, 156, 146),
            "accent": (224, 214, 204),
            "stem": (96, 88, 80),
            "stem_dark": (50, 45, 40),
            "glow": None,
        },
        "cap_style": "shards",
        "stem_style": "bark",
        "particle": {"style": "spark", "color": (0.78, 0.74, 0.70), "size": 0.04},
        "gen": underground((-50, 40), STONE, iterations=3, chance=(1, 6)),
        "habitat": "Cave floors and ravine ledges.",
        "desc": "Hardened fungal needles. They do not need to be touched hard to draw blood.",
    },
    {
        "key": "crimson_brain",
        "name": "Crimson Brain Fungus",
        "danger": 3,
        "shape": "brain",
        "range": 3.0,
        "damage": 0.0,
        "contact": 1.0,
        "pulse": 1,
        "effects": [("nausea", 120, 0), ("weakness", 120, 0)],
        "light": 0,
        "flammable": True,
        "palette": {
            "cap": (179, 39, 63),
            "cap_dark": (107, 15, 34),
            "cap_light": (224, 84, 112),
            "accent": (255, 154, 176),
            "stem": (130, 60, 70),
            "stem_dark": (72, 30, 38),
            "glow": None,
        },
        "cap_style": "folds",
        "stem_style": "fibrous",
        "particle": {"style": "drift", "color": (0.72, 0.20, 0.28), "size": 0.05},
        "gen": surface(["nether"], NETHER, iterations=2, chance=(1, 5)),
        "habitat": "Crimson forests and nether wastes.",
        "desc": "Folded like something that thinks. Being near it makes thinking harder.",
    },
    {
        "key": "glowspore",
        "name": "Glowspore",
        "danger": 2,
        "shape": "crust_nodule",
        "range": 5.0,
        "damage": 0.0,
        "contact": 0.0,
        "pulse": 1,
        "effects": [("mining_fatigue", 80, 0)],
        "light": 12,
        "flammable": False,
        "contaminates": True,
        "palette": {
            "cap": (31, 207, 194),
            "cap_dark": (11, 107, 101),
            "cap_light": (125, 245, 238),
            "accent": (201, 255, 251),
            "stem": (30, 150, 145),
            "stem_dark": (14, 80, 78),
            "glow": (150, 255, 248),
        },
        "cap_style": "nodules",
        "stem_style": "smooth",
        "particle": {"style": "rise", "color": (0.20, 0.90, 0.85), "size": 0.05, "glow": True},
        "gen": underground((-55, 25), STONE, iterations=3, chance=(1, 5)),
        "habitat": "Lush cave pockets and flooded tunnels.",
        "desc": "Lights a wide patch of tunnel and saturates all of it with heavy spores.",
    },
    {
        "key": "deathbell",
        "name": "Deathbell Mushroom",
        "danger": 4,
        "shape": "bell",
        "range": 4.0,
        "damage": 1.0,
        "contact": 2.0,
        "pulse": 1,
        "effects": [
            ("poison", 90, 1),
            ("weakness", 110, 0),
            ("slowness", 70, 0),
            ("blindness", 30, 0),
        ],
        "light": 0,
        "flammable": False,
        "palette": {
            "cap": (232, 228, 216),
            "cap_dark": (150, 146, 132),
            "cap_light": (255, 255, 248),
            "accent": (139, 139, 122),
            "stem": (46, 44, 44),
            "stem_dark": (22, 21, 21),
            "glow": None,
        },
        "cap_style": "pale",
        "stem_style": "ribbed",
        "particle": {"style": "sink", "color": (0.88, 0.87, 0.82), "size": 0.055},
        "gen": underground((-58, -5), DEEP, iterations=1, chance=(1, 16)),
        "habitat": "Deep caves and forgotten structures. Very rare.",
        "desc": "Pale bell on a black stalk. Everything it touches fails at once.",
    },
    {
        "key": "creeping_mold",
        "name": "Creeping Mold",
        "danger": 2,
        "shape": "crust_patch",
        "range": 3.0,
        "damage": 0.0,
        "contact": 0.0,
        "pulse": 1,
        "effects": [("weakness", 100, 0)],
        "light": 0,
        "flammable": True,
        "spreads": {"radius": 2, "max_nearby": 6, "chance": 0.25},
        "palette": {
            "cap": (47, 74, 42),
            "cap_dark": (22, 38, 15),
            "cap_light": (78, 122, 69),
            "accent": (14, 26, 12),
            "stem": (40, 60, 36),
            "stem_dark": (18, 30, 14),
            "glow": None,
        },
        "cap_style": "mottle",
        "stem_style": "smooth",
        "particle": {"style": "drift", "color": (0.18, 0.32, 0.16), "size": 0.045},
        "gen": surface(["swamp", "forest"], SWAMP, iterations=3, chance=(1, 5)),
        "habitat": "Damp stone and swamp mud. Spreads slowly.",
        "desc": "Black-green film that walks outward one block at a time, and only so far.",
    },
    {
        "key": "ash_fungus",
        "name": "Ash Fungus",
        "danger": 2,
        "shape": "cluster",
        "range": 3.0,
        "damage": 0.0,
        "contact": 0.0,
        "pulse": 1,
        "effects": [("weakness", 120, 0)],
        "light": 0,
        "flammable": False,
        "palette": {
            "cap": (154, 154, 150),
            "cap_dark": (86, 86, 84),
            "cap_light": (200, 200, 196),
            "accent": (58, 58, 56),
            "stem": (120, 120, 116),
            "stem_dark": (64, 64, 62),
            "glow": None,
        },
        "cap_style": "smoky",
        "stem_style": "bark",
        "particle": {"style": "smoke", "color": (0.55, 0.55, 0.54), "size": 0.075},
        "gen": surface(["nether", "mesa"], NETHER, iterations=3, chance=(1, 5)),
        "habitat": "Basalt deltas and burnt ground.",
        "desc": "Grey stalks that shed a constant dry smoke. Lungs give out before muscles do.",
    },
    {
        "key": "nightmare_cap",
        "name": "Nightmare Cap",
        "danger": 4,
        "shape": "cap_tall",
        "range": 4.0,
        "damage": 1.0,
        "contact": 1.0,
        "pulse": 1,
        "effects": [("darkness", 140, 0), ("slowness", 90, 1), ("nausea", 120, 0)],
        "light": 0,
        "flammable": True,
        "palette": {
            "cap": (107, 42, 138),
            "cap_dark": (53, 16, 63),
            "cap_light": (162, 75, 196),
            "accent": (224, 67, 92),
            "stem": (86, 62, 96),
            "stem_dark": (44, 30, 52),
            "glow": None,
        },
        "cap_style": "eyes",
        "stem_style": "ribbed",
        "particle": {"style": "sink", "color": (0.50, 0.20, 0.65), "size": 0.06},
        "gen": surface(["roofed_forest", "forest"], GROUND, iterations=1, chance=(1, 12)),
        "habitat": "Under dark oak canopy. Rare.",
        "desc": "Tall, watchful and wrong. Whatever it does to a mind, it does slowly.",
    },
    {
        "key": "parasite_bloom",
        "name": "Parasite Bloom",
        "danger": 4,
        "shape": "tendril",
        "range": 4.0,
        "damage": 0.0,
        "contact": 1.0,
        "pulse": 1,
        "effects": [],
        "light": 3,
        "flammable": True,
        "infects": True,
        "palette": {
            "cap": (232, 106, 158),
            "cap_dark": (138, 42, 85),
            "cap_light": (255, 166, 200),
            "accent": (255, 59, 107),
            "stem": (186, 96, 120),
            "stem_dark": (104, 48, 64),
            "glow": (255, 140, 180),
        },
        "cap_style": "tendrils",
        "stem_style": "fibrous",
        "particle": {"style": "rise", "color": (0.95, 0.42, 0.62), "size": 0.05, "glow": True},
        "gen": surface(["jungle", "swamp"], SWAMP, iterations=1, chance=(1, 13)),
        "habitat": "Jungle undergrowth and drowned roots. Rare.",
        "desc": "Seeds a fictional fungal infection that keeps working long after you walk away.",
    },
    {
        "key": "mycelium_x",
        "name": "Mycelium-X Core",
        "danger": 5,
        "shape": "core",
        "range": 6.0,
        "damage": 2.0,
        "contact": 3.0,
        "pulse": 1,
        "effects": [
            ("poison", 100, 1),
            ("weakness", 140, 1),
            ("slowness", 100, 1),
            ("nausea", 120, 0),
            ("darkness", 80, 0),
        ],
        "light": 6,
        "flammable": False,
        "contaminates": True,
        "infects": True,
        "spreads": {"radius": 2, "max_nearby": 4, "chance": 0.18},
        "palette": {
            "cap": (123, 63, 168),
            "cap_dark": (53, 19, 77),
            "cap_light": (176, 111, 224),
            "accent": (154, 255, 92),
            "stem": (76, 46, 100),
            "stem_dark": (38, 22, 52),
            "glow": (224, 179, 255),
        },
        "cap_style": "mutant",
        "stem_style": "bark",
        "particle": {"style": "burst", "color": (0.62, 0.35, 0.90), "size": 0.07, "glow": True},
        "gen": underground((-60, -35), DEEP, iterations=1, chance=(1, 40)),
        "habitat": "Only the deepest bedrock-adjacent voids. Extremely rare.",
        "desc": "A mutated fungal heart. It contaminates everything around it and keeps growing.",
    },
]

# --------------------------------------------------------------------------
# Equipment
# --------------------------------------------------------------------------

EQUIPMENT = [
    {
        "key": "fungal_scanner",
        "name": "Fungal Scanner",
        "kind": "tool",
        # No vanilla item group fits a scanner, and custom group names are not
        # supported at 1.21.0 - so it sits loose at the end of the Items tab.
        "group": None,
        "category": "items",
        "stack": 1,
        "desc": "Point it at the ground near a growth and use it for a full analysis readout.",
    },
    {
        "key": "spore_mask",
        "name": "Spore Mask",
        "kind": "armor",
        "slot": "slot.armor.head",
        "protection": 1,
        "durability": 220,
        "group": "itemGroup.name.helmet",
        "category": "equipment",
        "layer": 1,
        "desc": "A cloth filter. Blunts spore-borne effects a little; no protection from contact.",
    },
    {
        "key": "hazard_helmet",
        "name": "Hazard Helmet",
        "kind": "armor",
        "slot": "slot.armor.head",
        "protection": 3,
        "durability": 400,
        "group": "itemGroup.name.helmet",
        "category": "equipment",
        "layer": 1,
        "desc": "Sealed hood with its own air supply.",
    },
    {
        "key": "hazard_chestplate",
        "name": "Hazard Chestplate",
        "kind": "armor",
        "slot": "slot.armor.chest",
        "protection": 7,
        "durability": 580,
        "group": "itemGroup.name.chestplate",
        "category": "equipment",
        "layer": 1,
        "desc": "Rubberised containment suit torso.",
    },
    {
        "key": "hazard_leggings",
        "name": "Hazard Leggings",
        "kind": "armor",
        "slot": "slot.armor.legs",
        "protection": 5,
        "durability": 540,
        "group": "itemGroup.name.leggings",
        "category": "equipment",
        "layer": 2,
        "desc": "Reinforced containment suit legs.",
    },
    {
        "key": "hazard_boots",
        "name": "Hazard Boots",
        "kind": "armor",
        "slot": "slot.armor.feet",
        "protection": 3,
        "durability": 440,
        "group": "itemGroup.name.boots",
        "category": "equipment",
        "layer": 1,
        "desc": "Acid-resistant soles. Contact damage still gets through the worst species.",
    },
]

HAZARD_SET = [
    "hazard_helmet",
    "hazard_chestplate",
    "hazard_leggings",
    "hazard_boots",
]


def ident(key):
    return f"{NAMESPACE}:{key}"


def by_key(key):
    for spec in SPECIES:
        if spec["key"] == key:
            return spec
    raise KeyError(key)


assert len(SPECIES) == 20, "there must be exactly twenty species"
assert len({s["key"] for s in SPECIES}) == 20, "species keys must be unique"
assert len({s["name"] for s in SPECIES}) == 20, "species names must be unique"
